name: Check missing manifests

on:
  repository_dispatch:
    types: [check-missing-manifests]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Execute script with manifest entries
        env:
          C3_CLIENT_ID: ${{ secrets.C3_CLIENT_ID }}
          C3_CLIENT_SECRET: ${{ secrets.C3_CLIENT_SECRET }}
          CHECKBOX_COMMIT_STATUS_FPAT: ${{ secrets.CHECKBOX_COMMIT_STATUS_FPAT }}
          CHECKBOX_COMMIT: ${{ github.event.client_payload.commit }}
        run: |
          python utils/check_missing_manifests.py --manifest-entries "${{ github.event.client_payload.manifest-entries }}"
          RETCODE=$?
          URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          if [ $RETCODE -ne 0 ]; then
            echo "Some manifest entries are missing, sending commit status request 'failure'..."
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${CHECKBOX_COMMIT_STATUS_FPAT}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/canonical/checkbox/statuses/${CHECKBOX_COMMIT} \
              -d "{\"state\":\"failure\",\"target_url\":\"$URL\",\"context\":\"ce-oem-dut-checkbox-configuration\",\"description\":\"Manifest entries are missing.\"}"
          else
            echo "No manifest entries are missing, sending commit status request 'success'..."
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${CHECKBOX_COMMIT_STATUS_FPAT}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/canonical/checkbox/statuses/${CHECKBOX_COMMIT} \
              -d "{\"state\":\"success\",\"target_url\":\"$URL\",\"context\":\"ce-oem-dut-checkbox-configuration\",\"description\":\"No manifest entries are missing.\"}"
          fi
          exit $RETCODE

