name: Update the default manifest

on:
  push:
    branches: [ update_default_manifest ] 
  workflow_dispatch:

jobs:
  Update_default_manifest:
    name: Update default manifest
    runs-on: ubuntu-latest
    steps:
      - name: Install Checkbox
        run: |
          sudo add-apt-repository ppa:checkbox-dev/beta
          sudo apt-get update -qq
          sudo apt-get install canonical-certification-client -qq -y
      - name: Get latest manifest
        run: |
          # get the latest manifest
          checkbox-cli expand com.canonical.certification::client-cert-desktop-24-04 -f json|jq|grep "manifest entry" -2|grep has_|cut -d\" -f4|sort >>~/new.log
          cat ~/new.log
      - name: Checkout ce-oem-dut-checkbox-configuration
        uses: actions/checkout@v4
      - name: cat old default manifest
        run: |
          cat /home/runner/work/ce-oem-dut-checkbox-configuration/ce-oem-dut-checkbox-configuration/pc/default/manifest.json |grep has_|cut -d\" -f2|sort >>~/old.log
          cat ~/old.log
      - name: diff the old and new manifest
        run: |
          set +e
          echo "start test..."
          if [ ! -f ~/new.log ] || [ ! -f ~/old.log ]; then
            echo "new.log or old.log doesn't exist."
            exit 1
          fi
          echo "diff old.log new.log"
          diff ~/old.log ~/new.log > ~/diff.txt
          if [ $? -eq 0 ]; then
            echo "The manifest doesn't change!"
            exit 0
          else
            echo "The manifest has changed!"
            declare -A json_data
            while IFS= read -r line; do
                key=$(echo "$line"|tr -d ' \t')
                value=true
                if [[ -n "$key" ]]; then
                json_data["$key"]="$value"
                fi
            done < ~/new.log
            json_string=$(echo "$(declare -p json_data | sed 's/declare -A json_data=//;s/\"//g;s/\[/\"/g;s/\]/\"/g;s/=/:/g;s/ /,/g;s/,)/)/;s/(/\{/;s/)/\}/')")
            echo "$json_string" | jq > ~/manifest.json
            cat ~/manifest.json
            exit 0
          fi