name: Update the default manifest

on:
  push:
    branches: [ update_default_manifest ] 
  workflow_dispatch:

jobs:
  Update_default_manifest:
    name: Update default manifest
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install Checkbox
        run: |
          sudo add-apt-repository ppa:checkbox-dev/beta
          sudo apt-get update -qq
          sudo apt-get install canonical-certification-client -qq -y
      - name: Get latest manifest
        run: |
          # get the latest manifest
          checkbox-cli expand com.canonical.certification::client-cert-desktop-24-04 -f json|jq|grep "manifest entry" -2|grep has_|cut -d\" -f4|sort >>~/new.txt
          cat ~/new.txt
      - name: Checkout ce-oem-dut-checkbox-configuration
        uses: actions/checkout@v4
      - name: cat old default manifest
        run: |
          cat /home/runner/work/ce-oem-dut-checkbox-configuration/ce-oem-dut-checkbox-configuration/pc/default/manifest.json |grep has_|cut -d\" -f2|sort >>~/old.txt
          cat ~/old.txt
      - name: diff the old and new manifest
        run: |
          set +e
          echo "start test..."
          if [ ! -f ~/new.txt ] || [ ! -f ~/old.txt ]; then
            echo "~/new.txt or ~/old.txt doesn't exist."
            exit 0
          fi
          echo "diff ~/old.txt ~/new.txt"
          diff ~/old.txt ~/new.txt > diff.txt
          if [ $? -eq 0 ]; then
            echo "The manifest doesn't change!"
            exit 0
          else
            echo "The manifest has changed!"
            declare -A json_data
            while IFS= read -r line; do
                key=$(echo "$line"|tr -d ' \t')
                value=true
                if [[ -n "$key" ]]; then
                  json_data["$key"]="$value"
                fi
            done < ~/new.txt
            json_string=$(echo "$(declare -p json_data | sed 's/declare -A json_data=//;s/\"//g;s/\[/\"/g;s/\]/\"/g;s/=/:/g;s/ /,/g;s/,)/)/;s/(/\{/;s/)/\}/')")
            echo "$json_string" | jq > manifest.json
            cat manifest.json
            cp manifest.json /home/runner/work/ce-oem-dut-checkbox-configuration/ce-oem-dut-checkbox-configuration/pc/default/manifest.json
            exit 1
          fi
      - name: GIT commit and push all changed files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        if: failure()
        run: |
          git config --global user.name "eugene-yujinwu"
          git config --global user.email "eugene-yujinwu@users.noreply.github.com"
          git commit -a -m "update default manifest for pc"
          git push